# Generated by Django 4.1.2 on 2022-10-18 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_students'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classes',
            new_name='Module',
        ),
    ]
